import fs from 'node:fs';import assert from'node:assert/strict';import{PNG}from'pngjs';
const root='scratchpad/cozy-v3';const report=JSON.parse(fs.readFileSync(root+'/renders/report.json'));
assert.deepEqual(report.before,report.after);assert.equal(report.errors.length,0);assert(report.connectedRoute);assert.equal(report.views.length,10);assert.equal(report.treeScale,1.5);
for(const v of report.views){const p=PNG.sync.read(fs.readFileSync(root+'/renders/'+v.id+'.png'));assert.equal(p.width,1920);assert.equal(p.height,1200);}
const order=[6,2,3,4,7,8,9,5,1,0];const views=order.map(i=>report.views[i]);
fs.writeFileSync(root+'/gallery.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Terepasztal · Cozy world</title><style>*{box-sizing:border-box}body{margin:0;background:#19271f;color:#e4d5b5;font:16px/1.6 system-ui}main{max-width:1500px;margin:auto;padding:36px 28px}h1{font:500 40px Georgia,serif;margin:12px 0}p,small{color:#b9c5b0}a{color:#e4d5b5}nav{display:flex;gap:8px;flex-wrap:wrap;margin:26px 0}nav a{padding:6px 13px;border:1px solid #52624e;border-radius:25px;text-decoration:none}figure{margin:32px 0 60px}figcaption{font:500 25px Georgia,serif;margin-bottom:12px}img{display:block;width:100%;height:auto;border:1px solid #53664e}.note{padding:18px 24px;background:#223428;border-left:3px solid #9eae75}</style><main><small>TEREPASZTAL / COZY WORLD / V3</small><h1>A railway that belongs in its landscape.</h1><p>Ten actual game views · Normally generated 128 × 128 map · Seed 7412 · All six biomes.</p><p>Continuous ground, irregular transitions and connected hills. Larger tree variants, softer building contact edges, taller water-tower supports and a smaller kiln. Warm windows, rain and mist.</p><p class="note">The game now opens with the original Pastoral Pulse, then shuffles all four arrangements. Nature and weather sounds have their own volume control. Music begins after a click or keypress in the game.</p><nav>${views.map(v=>`<a href="#${v.id}">${v.title.split(' · ')[0]}</a>`).join('')}<a href="#playable">Normal play screen</a></nav>${views.map(v=>`<figure id="${v.id}"><figcaption>${v.title}</figcaption><a href="renders/${v.id}.png"><img loading="lazy" src="renders/${v.id}.png" alt="${v.title}"></a></figure>`).join('')}<figure id="playable"><figcaption>Normal play screen · production build</figcaption><a href="renders/11-playable-build.png"><img loading="lazy" src="renders/11-playable-build.png" alt="Production game with its normal UI"></a></figure><p class="note">The shared human/door scale is enforced for calibrated building families and their levels. Equipment without a measured reference remains explicitly estimated. These screenshots use the production assets; the earlier reconstructed Rocket remains a separate QA candidate.</p><p><a href="README.md">Review notes</a> · <a href="renders/verification.json">Browser checks</a> · <a href="renders/motion.json">Moving-train checks</a></p></main>`);
const dest='G:/DEV/Terepasztal/renders/cozy-v3';fs.mkdirSync(dest,{recursive:true});
for(const file of ['gallery.html','README.md','scene.js','index.html','capture.mjs','verify.mjs','motion.mjs','production.mjs','publish.mjs'])fs.copyFileSync(root+'/'+file,dest+'/'+file);
fs.cpSync(root+'/renders',dest+'/renders',{recursive:true});
fs.copyFileSync('docs/art-direction/cozy-v3.md',dest+'/implementation-notes.md');
fs.mkdirSync('G:/DEV/Terepasztal/assets/source/cozy-v3',{recursive:true});fs.cpSync('assets/source/cozy-v3','G:/DEV/Terepasztal/assets/source/cozy-v3',{recursive:true});
console.log(JSON.stringify({views:11,seed:report.seed,destination:dest,generatedSourceAssets:4}));
