import { describe, expect, it } from 'vitest';
import { Container, Rectangle, Sprite, Texture, TextureSource } from 'pixi.js';
import type { FrameInfo } from '../engine/atlas';
import { structureScale, TREE_SCALE } from './assetScale';
import { WorldRenderer } from './worldRenderer';

const SOURCE = new TextureSource({ width: 1024, height: 1024 });

/** A frame `w` x `h` world px across, at `resolution` texels per px; its pixels are never read. */
function frame(w: number, h: number, resolution = 1): FrameInfo {
  return {
    image: undefined as never,
    texture: new Texture({
      source: SOURCE,
      frame: new Rectangle(0, 0, w * resolution, h * resolution),
      orig: new Rectangle(0, 0, w, h),
    }),
    anchorX: 0.5,
    anchorY: 0.9,
    w,
    h,
  };
}

const FRAMES: Record<string, FrameInfo> = {
  'structures/water_tower': frame(40, 60),
  'structures/water_tower_r2': frame(40, 60),
  'structures/power_line': frame(16, 40),
  'structures/depot_r1': frame(90, 70),
  'structures/station_1': frame(50, 42.25, 4),
  'structures/station_1_r1': frame(60, 55),
  'structures/townhouse_s1': frame(40, 50),
  'structures/townhouse_s1_r3': frame(40, 50),
  'terrain/ghost_ok': frame(64, 32),
  'props/oak_2': frame(20, 30),
};

/**
 * A world renderer with only what placing a structure touches: the atlas above, a one-tile map,
 * its two layers, and surfaces that hand back textures without reading pixels (Node has no
 * canvas). `families` records the window-light family each building was lit with.
 */
function renderer() {
  const objects = new Container(),
    contactGround = new Container(),
    families: string[] = [];
  const world = Object.create(WorldRenderer.prototype) as WorldRenderer;
  Object.assign(world, {
    atlas: { has: (k: string) => k in FRAMES, get: (k: string) => FRAMES[k] },
    map: { w: 1, h: 1, originX: 0, originY: 0, terrain: [0], biome: [0] },
    objects,
    contactGround,
    structures: new Map(),
    structureAnchors: new Map(),
    windowLights: new Map(),
    contactPatches: new Map(),
    surfaces: {
      contact: () => Texture.EMPTY,
      window: (_key: string, _f: FrameInfo, _procedural: boolean, family: string) => {
        families.push(family);
        return Texture.EMPTY;
      },
      groundContour: () => [{ x: 0, y: 0 }],
    },
    elevationOf: () => 0,
    refreshScatter: () => {},
  });
  const lights = () => objects.children.filter((c) => c.label === 'emissive').length;
  return { world, lights, patches: () => contactGround.children.length, families };
}

describe('a structure sprite switching frames', () => {
  it('takes its new frame size, lights and patches, never the frame before', () => {
    const { world, lights, patches, families } = renderer();
    const s = world.setStructure('decor:0,0', 0, 0, 'structures/water_tower');
    expect(s.scale.x).toBeCloseTo(0.7, 9);
    expect([lights(), patches()]).toEqual([1, 1]);
    // the same sprite shows a frame with no scale reference: scale 1, no lights, no patches
    expect(world.setStructure('decor:0,0', 0, 0, 'structures/power_line')).toBe(s);
    expect([s.scale.x, s.scale.y]).toEqual([1, 1]);
    expect([lights(), patches()]).toEqual([0, 0]);
    // and back to a building, turned this time: its unturned frame's size and lights
    world.setStructure('decor:0,0', 0, 0, 'structures/water_tower_r2');
    expect(s.scale.x).toBeCloseTo(0.7, 9);
    expect([lights(), patches()]).toEqual([1, 1]);
    expect(families.at(-1)).toBe('water_tower');
    world.setStructure('decor:0,0', 0, 0, 'structures/depot_r1');
    expect(s.scale.x).toBe(1);
    expect([lights(), patches()]).toEqual([0, 0]);
  });

  it('lights a turned house with its unturned family', () => {
    const { world, families } = renderer();
    const s = world.setStructure('decor:0,0', 0, 0, 'structures/townhouse_s1_r3');
    expect(s.scale.x).toBeCloseTo(structureScale('structures/townhouse_s1'), 9);
    expect(families).toEqual(['townhouse']);
  });

  it('measures each picture by its own door: illustrated by height, generated by reference', () => {
    const { world } = renderer();
    const s = world.setStructure('station:1', 0, 0, 'structures/station_1');
    expect(s.scale.x).toBeCloseTo(structureScale('structures/station_1', 42.25), 9);
    // the turn is a generated picture, so its door is the generator's reference door
    world.setStructure('station:1', 0, 0, 'structures/station_1_r1');
    expect(s.scale.x).toBeCloseTo(structureScale('structures/station_1'), 9);
  });
});

describe('a ghost sprite switching frames', () => {
  it('takes each new frame size', () => {
    const { world } = renderer();
    const g = new Sprite();
    const steps: [string, number][] = [
      ['structures/water_tower', 0.7],
      ['structures/water_tower_r2', 0.7],
      ['terrain/ghost_ok', 1],
      ['structures/water_tower_r2', 0.7],
      ['props/oak_2', TREE_SCALE],
      ['structures/depot_r1', 1],
    ];
    for (const [key, scale] of steps) {
      world.setSpriteFrame(g, key);
      expect(g.scale.x, key).toBeCloseTo(scale, 9);
      expect(g.scale.y, key).toBeCloseTo(scale, 9);
    }
  });
});
