import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { Container, Rectangle, Sprite, Texture, TextureSource } from 'pixi.js';
import type { FrameInfo } from '../engine/atlas';
import { emptyMap } from '../world/mapgen';
import { Terrain } from '../world/tiles';
import { structureScale, TREE_SCALE } from './assetScale';
import { Landscape, type PainterPool } from './landscape';
import { buildRelief, groundAllows } from './terrainRelief';
import { WorldRenderer } from './worldRenderer';

const SOURCE = new TextureSource({ width: 1024, height: 1024 });

/** A frame `w` x `h` world px across, at `resolution` texels per px; its pixels are never read. */
function frame(w: number, h: number, resolution = 1): FrameInfo {
  return {
    image: undefined as never,
    texture: new Texture({
      source: SOURCE,
      frame: new Rectangle(0, 0, w * resolution, h * resolution),
      orig: new Rectangle(0, 0, w, h),
    }),
    anchorX: 0.5,
    anchorY: 0.9,
    w,
    h,
  };
}

const FRAMES: Record<string, FrameInfo> = {
  'structures/water_tower': frame(40, 60),
  'structures/water_tower_r2': frame(40, 60),
  'structures/power_line': frame(16, 40),
  'structures/depot_r1': frame(90, 70),
  'structures/station_1': frame(50, 42.25, 4),
  'structures/station_1_r1': frame(60, 55),
  'structures/townhouse_s1': frame(40, 50),
  'structures/townhouse_s1_r3': frame(40, 50),
  'terrain/ghost_ok': frame(64, 32),
  'props/oak_2': frame(20, 30),
};

/**
 * A world renderer with only what placing a structure touches: the atlas above, a one-tile map,
 * its two layers, and surfaces that hand back textures without reading pixels (Node has no
 * canvas). `families` records the window-light family each building was lit with.
 */
function renderer() {
  const objects = new Container(),
    contactGround = new Container(),
    families: string[] = [];
  const world = Object.create(WorldRenderer.prototype) as WorldRenderer;
  Object.assign(world, {
    atlas: { has: (k: string) => k in FRAMES, get: (k: string) => FRAMES[k] },
    map: { w: 1, h: 1, originX: 0, originY: 0, terrain: [0], biome: [0] },
    objects,
    contactGround,
    structures: new Map(),
    structureAnchors: new Map(),
    windowLights: new Map(),
    contactPatches: new Map(),
    surfaces: {
      contact: () => Texture.EMPTY,
      window: (_key: string, _f: FrameInfo, _procedural: boolean, family: string) => {
        families.push(family);
        return Texture.EMPTY;
      },
      groundContour: () => [{ x: 0, y: 0 }],
    },
    elevationOf: () => 0,
    refreshScatter: () => {},
  });
  const lights = () => objects.children.filter((c) => c.label === 'emissive').length;
  return { world, lights, patches: () => contactGround.children.length, families };
}

describe('a structure sprite switching frames', () => {
  it('takes its new frame size, lights and patches, never the frame before', () => {
    const { world, lights, patches, families } = renderer();
    const s = world.setStructure('decor:0,0', 0, 0, 'structures/water_tower');
    expect(s.scale.x).toBeCloseTo(0.7, 9);
    expect([lights(), patches()]).toEqual([1, 1]);
    // the same sprite shows a frame with no scale reference: scale 1, no lights, no patches
    expect(world.setStructure('decor:0,0', 0, 0, 'structures/power_line')).toBe(s);
    expect([s.scale.x, s.scale.y]).toEqual([1, 1]);
    expect([lights(), patches()]).toEqual([0, 0]);
    // and back to a building, turned this time: its unturned frame's size and lights
    world.setStructure('decor:0,0', 0, 0, 'structures/water_tower_r2');
    expect(s.scale.x).toBeCloseTo(0.7, 9);
    expect([lights(), patches()]).toEqual([1, 1]);
    expect(families.at(-1)).toBe('water_tower');
    world.setStructure('decor:0,0', 0, 0, 'structures/depot_r1');
    expect(s.scale.x).toBe(1);
    expect([lights(), patches()]).toEqual([0, 0]);
  });

  it('lights a turned house with its unturned family', () => {
    const { world, families } = renderer();
    const s = world.setStructure('decor:0,0', 0, 0, 'structures/townhouse_s1_r3');
    expect(s.scale.x).toBeCloseTo(structureScale('structures/townhouse_s1'), 9);
    expect(families).toEqual(['townhouse']);
  });

  it('measures each picture by its own door: illustrated by height, generated by reference', () => {
    const { world } = renderer();
    const s = world.setStructure('station:1', 0, 0, 'structures/station_1');
    expect(s.scale.x).toBeCloseTo(structureScale('structures/station_1', 42.25), 9);
    // the turn is a generated picture, so its door is the generator's reference door
    world.setStructure('station:1', 0, 0, 'structures/station_1_r1');
    expect(s.scale.x).toBeCloseTo(structureScale('structures/station_1'), 9);
  });
});

describe('a ghost sprite switching frames', () => {
  it('takes each new frame size', () => {
    const { world } = renderer();
    const g = new Sprite();
    const steps: [string, number][] = [
      ['structures/water_tower', 0.7],
      ['structures/water_tower_r2', 0.7],
      ['terrain/ghost_ok', 1],
      ['structures/water_tower_r2', 0.7],
      ['props/oak_2', TREE_SCALE],
      ['structures/depot_r1', 1],
    ];
    for (const [key, scale] of steps) {
      world.setSpriteFrame(g, key);
      expect(g.scale.x, key).toBeCloseTo(scale, 9);
      expect(g.scale.y, key).toBeCloseTo(scale, 9);
    }
  });
});

/** A paint worker that hears everything and answers nothing. */
const quietWorker = () => ({
  onmessage: null,
  onerror: null,
  postMessage: () => {},
  terminate: () => {},
});
type Quiet = ReturnType<typeof quietWorker>;

/** A world renderer with only what the building rules ask of it: a landscape and its map. */
function groundOf(map: ReturnType<typeof emptyMap>, painters: PainterPool) {
  const landscape = new Landscape(map, new Set(), new Map(), painters);
  const world = Object.create(WorldRenderer.prototype) as WorldRenderer;
  Object.assign(world, { landscape, map });
  return { world, landscape };
}
/** Workers that loaded their sheet: painting, and active from the first flush. */
function working(map: ReturnType<typeof emptyMap>) {
  const spawned: Quiet[] = [];
  const g = groundOf(map, {
    size: 2,
    spawn: () => {
      const w = quietWorker();
      spawned.push(w);
      return w as unknown as Worker;
    },
    sheet: () => 'test://terrain-surfaces.png',
  });
  (spawned[0].onmessage as unknown as (e: { data: object }) => void)?.({ data: { loaded: true } });
  g.landscape.flush();
  expect(g.landscape.active).toBe(true);
  return g;
}
/** Workers that cannot start, twice: the landscape is off for the session. */
function failed(map: ReturnType<typeof emptyMap>) {
  const g = groundOf(map, {
    size: 2,
    spawn: () => {
      throw new Error('Worker is not defined');
    },
    sheet: () => 'test://terrain-surfaces.png',
  });
  expect(g.landscape.failed).toBe(true);
  return g;
}
/** A 32 x 32 map of hills with a mountain in them, as terrainRelief.test.ts walks. */
function hills() {
  const m = emptyMap(7412, 32, 32);
  for (let y = 3; y < 29; y++)
    for (let x = 3; x < 29; x++)
      m.terrain[y * 32 + x] = x > 7 && x < 25 && y > 7 && y < 25 ? Terrain.Mountain : Terrain.Hill;
  return m;
}

describe('the building rules on slopes', () => {
  beforeEach(() => {
    vi.spyOn(console, 'error').mockImplementation(() => {});
    vi.spyOn(console, 'warn').mockImplementation(() => {});
  });
  afterEach(() => vi.restoreAllMocks());

  it('answer alike while the painter works and after it has failed, as the relief says', () => {
    const map = hills(),
      relief = buildRelief(map, new Set(), undefined, new Map());
    const ok = working(hills()).world,
      lost = failed(hills()).world;
    let refused = 0,
      allowed = 0;
    // every tile and the ring just outside the map, for both needs
    for (let y = -1; y <= map.h; y++)
      for (let x = -1; x <= map.w; x++)
        for (const need of ['straight', 'level'] as const) {
          const expected = groundAllows(map, relief, x, y, need);
          expect(ok.groundAllows(x, y, need), `working, ${need} at ${x},${y}`).toBe(expected);
          expect(lost.groundAllows(x, y, need), `failed, ${need} at ${x},${y}`).toBe(expected);
          if (expected) allowed++;
          else refused++;
        }
    expect(refused).toBeGreaterThan(0);
    expect(allowed).toBeGreaterThan(0);
    // a bank is refused level ground and a tile outside the map is refused outright
    expect(lost.groundAllows(3, 3, 'level')).toBe(false);
    expect(lost.groundAllows(-1, 0, 'straight')).toBe(false);
  });

  it('follow the terrain changed after the failure, as they do while the painter works', () => {
    const grow = (world: WorldRenderer, landscape: Landscape, map: ReturnType<typeof emptyMap>) => {
      const before = world.groundAllows(14, 16, 'level');
      for (let y = 14; y < 19; y++)
        for (let x = 14; x < 19; x++) {
          map.terrain[y * map.w + x] = Terrain.Hill;
          landscape.invalidate(x, y);
        }
      return [before, world.groundAllows(14, 16, 'level'), world.groundAllows(16, 16, 'level')];
    };
    const flat = () => emptyMap(7412, 32, 32);
    const [a, b] = [flat(), flat()];
    const ok = working(a),
      lost = failed(b);
    // open ground first, then the hill's foot is a bank and its top is level again
    expect(grow(ok.world, ok.landscape, a)).toEqual([true, false, true]);
    expect(grow(lost.world, lost.landscape, b)).toEqual([true, false, true]);
  });
});
