import { launch } from '../runtime.mjs';
const [url, out, w, h] = process.argv.slice(2);
const b = await launch();
const p = await b.newPage({ viewport: { width: Number(w ?? 1440), height: Number(h ?? 1000) } });
const errs = [];
p.on('pageerror', (e) => errs.push(e.message));
await p.goto(url);
await p.waitForFunction(() => typeof window.qa?.shot === 'function', null, { timeout: 180000 });
const r = await p.evaluate(() => qa.shot());
await p.screenshot({ path: out });
console.log(JSON.stringify(r), errs);
await b.close();
