/** All user-facing strings. Keep flat so a Hungarian table can mirror this file later. */
export const STR = {
  title: 'Terepasztal',
  loading: 'Laying the first sleepers...',
  hud: {
    money: 'Funds',
    tickets: 'Tickets',
    reputation: 'Reputation',
    day: (d: number) => `Day ${d}`,
    speed: ['Paused', '1x', '2x', '3x'],
    tier: (t: number) => `Tier ${t}`,
    tierUp: (t: number) => `Reputation tier ${t} reached. New regions charted.`,
  },
  overview: {
    locked: 'UNCHARTED',
    tierReq: (t: number) => `Reputation tier ${t}`,
    hint: 'Tab / scroll in: return to field view',
  },
  hints: {
    camera: 'WASD / arrows / middle-drag: pan   wheel: zoom   Tab: overview   `: debug',
  },
  debug: {
    title: 'Debug',
    fps: 'FPS',
    seed: 'Seed',
    entities: 'Entities',
    giveMoney: '+10,000 funds',
    giveTickets: '+10 tickets',
    giveRep: '+100 rep',
    spawnContract: 'Spawn contract',
    depthOverlay: 'Depth-sort overlay',
    zoom: 'Zoom',
    camera: 'Camera',
    tile: 'Tile',
    regenerate: 'New map (seed)',
  },
  minimap: { title: 'Survey' },
  build: {
    offMap: 'Outside the map',
    locked: 'Uncharted region',
    rock: 'Cannot lay track on rock',
    needBridge: 'Water needs a bridge',
    bridgeOnWater: 'Bridges only span water',
    occupied: 'Tile occupied',
    funds: 'Not enough funds',
    tierLocked: (t: number) => `Requires reputation tier ${t}`,
    badTerrain: 'Cannot build here',
    needTrack: 'Must touch track',
    levelCap: 'Level cap for your reputation tier',
    cost: (v: string) => `Cost ${v}`,
    refund: (v: string) => `Refund ${v}`,
    rotate: 'R: rotate',
    dragHint: 'drag to lay a line',
  },
  toolbar: {
    track: 'Track',
    stations: 'Stations',
    remove: 'Remove',
    removeHint: 'Right-click / Delete removes',
    select: 'Select',
  },
  depot: {
    title: 'Depot',
    trains: 'Trains in service',
    consist: 'Consist',
    route: 'Route (looped)',
    newTrain: 'New train',
    noTrains: 'No trains yet. Pick a locomotive, wagons and at least two stops.',
    locate: 'Locate',
    editRoute: 'Route',
    recall: 'Recall',
    locomotive: 'Locomotive',
    wagons: 'Wagons',
    noFreeLoco: 'No free locomotives. Recall a train or pull from the gacha.',
    noFreeWagons: 'No free wagons.',
    speed: 'Speed',
    power: 'Power',
    weight: 'Weight',
    empty: 'Empty',
    pickLoco: 'Pick a locomotive',
    maxWagons: (n: number) => `This locomotive pulls at most ${n} wagons`,
    stops: 'Stops',
    noStops: 'No stops. Add stations below.',
    addStop: 'Add stop',
    noStations: 'Build stations first.',
    applyRoute: 'Apply route',
    dispatch: 'Dispatch',
    namePlaceholder: 'Train name',
    needTwoStops: 'Route needs at least two stops',
    routeApplied: (n: string) => `${n}: route updated`,
    dispatched: (n: string) => `${n} dispatched`,
    editingConsist: (n: string) => `Editing route of ${n}. Recall it to change its consist.`,
    cargo: (n: number) => `${n}u aboard`,
    fuelHint: (v: string) => `Running cost per tile from ${v}`,
    state: {
      moving: 'En route',
      loading: 'At platform',
      waiting: 'Waiting for platform',
      noRoute: 'No route',
      stranded: 'Stranded',
    } as Record<string, string>,
  },
  topbar: {
    depot: 'Depot',
    contracts: 'Contracts',
    gacha: 'Gacha',
    roster: 'Roster',
    settings: 'Settings',
  },
  station: {
    level: (l: number) => `Level ${l}`,
    produces: 'Produces',
    accepts: 'Accepts',
    storage: 'Storage',
    platforms: 'Platforms',
    loadRate: 'Loading',
    perDay: (v: number) => `${v} / day`,
    perSec: (v: number) => `${v} / s`,
    upgrade: 'Upgrade',
    upgradeTo: (l: number, cost: string) => `Upgrade to ${l} (${cost})`,
    maxed: 'Max level',
    unlocks: (c: string) => `Next: ${c}`,
    demolish: 'Demolish',
    rename: 'Rename',
    noPlatform: 'No adjacent track!',
  },
} as const;
