/** All user-facing strings. Keep flat so a Hungarian table can mirror this file later. */
export const STR = {
  title: 'Terepasztal',
  loading: 'Laying the first sleepers...',
  hud: {
    money: 'Funds',
    weather: (season: string, weather: string) => `${season} · ${weather}`,
    tickets: 'Tickets',
    reputation: 'Reputation',
    day: (d: number) => `Day ${d}`,
    speed: ['❚❚', '1x', '2x', '3x'],
    pause: 'Pause (Space)',
    resume: 'Resume (Space)',
    weatherToggle: 'Weather',
    weatherToggleHint: 'Toggle rain, fog and seasons',
    dayToggle: 'Day/night',
    dayToggleHint: 'Toggle the day and night cycle',
    tier: (t: number) => `Tier ${t}`,
    tierUp: (t: number) => `Reputation tier ${t} reached. New rolling stock and works unlocked.`,
  },
  overview: {
    locked: 'UNCHARTED',
    tierReq: (t: number) => `Reputation tier ${t}`,
    price: (v: number) => `$${v.toLocaleString()}`,
    buyHint: 'click to buy',
    buyConfirm: (v: string) => `Buy this chunk for ${v}?`,
    bought: 'Chunk charted. Neighbouring land is now visible.',
    cannotAfford: (v: string) => `Need ${v} to buy this chunk`,
    chunkTitle: 'Uncharted chunk',
    chunkLines: (v: string) => [`Price ${v}`, 'Click to buy'],
    hint: 'M / scroll in: return to field view',
  },
  hints: {
    camera: 'WASD / arrows / middle-drag: pan   wheel: zoom   M: overview   `: debug',
  },
  debug: {
    title: 'Debug',
    fps: 'FPS',
    seed: 'Seed',
    entities: 'Entities',
    giveMoney: '+10,000 funds',
    giveTickets: '+10 tickets',
    giveRep: '+100 rep',
    giveResources: '+200 resources',
    spawnContract: 'Spawn contract',
    depthOverlay: 'Depth-sort overlay',
    zoom: 'Zoom',
    camera: 'Camera',
    tile: 'Tile',
    regenerate: 'New map (seed)',
  },
  minimap: { title: 'Survey' },
  build: {
    offMap: 'Outside the map',
    locked: 'Uncharted region',
    rock: 'Cannot lay track on rock',
    needBridge: 'Water needs a bridge',
    bridgeOnWater: 'Bridges only span water',
    occupied: 'Tile occupied',
    funds: 'Not enough funds',
    tierLocked: (t: number) => `Requires reputation tier ${t}`,
    badTerrain: 'Cannot build here',
    needTrack: 'Must touch track',
    needTrackHere: 'Signals stand on track',
    needResources: (m: string) => `Need ${m}`,
    replace: (what: string, net: string) => `Replace ${what}: net ${net}`,
    levelCap: 'Level cap for your reputation tier',
    cost: (v: string) => `Cost ${v}`,
    refund: (v: string) => `Refund ${v}`,
    rotate: 'R: rotate',
    dragHint: 'drag to lay a line',
  },
  toolbar: {
    track: 'Track',
    stations: 'Stations',
    remove: 'Remove',
    decor: 'Decor',
    buildings: 'Works',
    services: 'Services',
    utility: 'Utility',
    removeHint: 'Right-click / Delete removes',
    select: 'Select',
    cycleHint: '1-9 or Tab: switch item · Esc: close',
    place: {
      track: 'On grass, forest, sand or hill. Not on rock; water needs a bridge.',
      bridge: 'Only on a water tile, joining track on both banks.',
      station: 'On a buildable tile with track touching one side; that track becomes the platform.',
      onTrack: 'On an existing track tile. R rotates.',
      service: (r: number) => `On a free tile within ${r} tiles of the stations it should serve.`,
      powerLine:
        'On track or any free tile. Poles link within 2 tiles of each other and of a Power Plant; rails within 1 tile of a live pole are powered.',
      building: 'On a free buildable tile.',
      works: 'On a free buildable tile. Runs from the stockpile; no track needed.',
      plant: 'On a free buildable tile. Chain Power Line poles from it to reach the rails.',
    },
    trackDesc: {
      straight: 'Plain rail. Drag to lay a run of straights.',
      curve: 'Quarter turn. R rotates.',
      switch: 'Junction: one line splits into two. Trains take whichever branch their route needs.',
      crossing: 'Two lines cross without connecting.',
      bridge: 'Spans one tile of water. Only on water.',
    } as Record<string, string>,
  },
  building: {
    recipe: 'Recipe',
    rate: 'Current rate',
    maxRate: 'Full rate',
    status: 'Status',
    progress: 'Batch progress',
    crew: 'Crew',
    made: 'Produced so far',
    inStock: (n: string) => `${n} in stockpile`,
    running: 'Running',
    full: 'Stopped: stockpile full',
    starved: (n: string) => `Waiting for ${n}`,
    or: 'or',
  },
  notice: {
    title: 'Notices',
    none: 'All quiet.',
    more: (n: number) => `+${n} more`,
    outOfFuel: (n: string) => `${n}: out of fuel or water`,
    noPower: (n: string) => `${n}: no power on this line`,
    overweight: (n: string) => `${n}: too heavy for its engines`,
    noRoute: (n: string) => `${n}: no route to its next stop`,
    ecoMode: (n: string) => `${n}: low on fuel, crawling to save it`,
    held: (n: string) => `${n}: held by traffic`,
    orphaned: (n: string) => `${n}: no platform track`,
    unwired: (n: string) => `${n}: no power line connected`,
    starved: (n: string, r: string) => `${n}: waiting for ${r}`,
    full: (n: string) => `${n}: stockpile full, output stopped`,
    contractFailed: (n: string) => `Contract failed: ${n}`,
    contractDone: (n: string) => `Contract completed: ${n}`,
    famine: 'Crews are out of wheat',
  },
  advisor: {
    button: 'Advisor',
    title: 'Advisor',
    silence: 'Silence',
    unsilence: 'Unsilence',
    silencedHint: 'The advisor is silenced. Unsilence it to see tips again.',
    allGood: 'Nothing to advise right now. Keep the trains rolling.',
    tips: {
      noStations:
        'Build a producing station (farm, lumber yard, quarry or pump) and a second station, joined by track.',
      oneStation:
        'Build a second station and connect the two with track so a train has somewhere to go.',
      noPlatform: (n: string) =>
        `${n} has no track next to it. Lay a straight piece touching the station.`,
      noTrain:
        'Open the Depot (F), pick the locomotive and wagons and press Dispatch. The route is automatic.',
      idleStock: (n: number) =>
        `${n} locomotive(s) sit idle in the depot. Dispatch them to earn more.`,
      lowWheat:
        'Wheat is running low for the crews. Build a farm and route a train through it, or buy wheat on the Market (K).',
      famine:
        'The crews are starving: production halved. Get wheat in by train or from the Market (K).',
      outOfFuel: (n: string) =>
        `${n} is out of fuel. Fill the stockpile (Market K, a kiln or a lumber yard for wood) or use Emergency refuel in the train details.`,
      lowCoal:
        'Coal is short. Build a Charcoal Kiln (Works) to turn wood into coal, or buy coal on the Market.',
      noWater:
        'No water source. Build a Water Pump station or a Water Tower so steam engines can refill.',
      unwired: (n: string) =>
        `${n} is not connected. Chain Power Line poles from it to the rails (Utility).`,
      noPower: (n: string) =>
        `${n} needs powered rails: build a Power Plant and Power Line poles along its route.`,
      chunk: (v: string) =>
        `You can afford a new chunk (${v}). Press M and click an Uncharted chunk to expand.`,
      offers: (n: number) => `${n} contract offer(s) are waiting on the Contract Board (C).`,
      failed: (n: string) =>
        `Contract "${n}" failed. Accept only contracts your trains already pass through, and watch the deadline.`,
      capFull: (r: string) =>
        `The stockpile is full of ${r}. Upgrade or build a Warehouse to raise the cap, or sell on the Market.`,
      blocked: (n: string) =>
        `${n} is stuck behind another train. Add a passing loop with switches or a second track.`,
    },
  },
  trainSide: {
    title: 'Trains in view',
    titleAll: 'All trains',
    none: 'No trains in service.',
    noneVisible: 'No trains on screen.',
    tilesPerSec: 'tiles/s',
    speed: 'Speed',
    capacity: 'Capacity',
    tanks: 'Tanks',
    fuel: 'Fuel',
    perTile: '/ tile',
    perWeek: 'Per week',
    consumes: 'Consumes',
    collects: 'Collects',
    delivers: 'Delivers',
    noData: 'after first loop',
    hoverHint: 'Hover a train to trace its path',
  },
  depot: {
    title: 'Depot',
    trains: 'Trains in service',
    consist: 'Consist',
    route: 'Route (looped)',
    newTrain: 'New train',
    noTrains: 'No trains yet. Pick a locomotive and wagons; the route is automatic.',
    routeAuto: 'Automatic route',
    routeCustom: 'Custom route',
    routeAutoHint:
      'The train visits every station with platform track, nearest first. Change stops later in the train details.',
    locate: 'Locate',
    editRoute: 'Route',
    recall: 'Recall',
    locomotive: 'Locomotive',
    wagons: 'Wagons',
    noFreeLoco: 'No free locomotives. Recall a train or pull from the gacha.',
    noFreeWagons: 'No free wagons.',
    speed: 'Speed',
    power: 'Power',
    weight: 'Weight',
    empty: 'Empty',
    pickLoco: 'Pick a locomotive',
    maxWagons: (n: number) => `This locomotive pulls at most ${n} wagons`,
    stops: 'Stops',
    noStops: 'No stops. Add stations below.',
    addStop: 'Add stop',
    noStations: 'Build stations first.',
    applyRoute: 'Apply route',
    dispatch: 'Dispatch',
    namePlaceholder: 'Train name',
    needTwoStops: 'Route needs at least two stops',
    routeApplied: (n: string) => `${n}: route updated`,
    dispatched: (n: string) => `${n} dispatched`,
    editingConsist: (n: string) => `Editing route of ${n}. Recall it to change its consist.`,
    cargo: (n: number) => `${n}u aboard`,
    fuelHint: (v: string) => `Running cost per tile from ${v}`,
    details: 'Details',
    haul: (w: number, p: number) => `Wagons ${w} t of ${p} t the engines can haul (before cargo)`,
    scheduleHint: 'Stops, loading and departure direction are edited in the train details.',
    scheduleLiveHint:
      'Changes apply at once. Each stop: what to load and unload, wait for full wagons, refuel, and which way to leave.',
    stockpileTag: 'stockpile',
    fuelTag: 'refuel',
    waterTag: 'water',
    opt: {
      loadAuto: 'Load: auto',
      loadNone: 'Load: nothing',
      unloadAll: 'Unload: all',
      unloadNone: 'Unload: nothing',
      departAuto: 'Depart: auto',
      departForward: 'Depart: forward',
      departReverse: 'Depart: reverse',
      waitFull: 'Wait full',
      refuel: 'Refuel',
      pass: 'Pass through',
      plain: 'stop, load, unload',
    },
    salvaged: (v: string) => `Cargo aboard salvaged for ${v}`,
    state: {
      moving: 'En route',
      loading: 'At platform',
      waiting: 'Waiting for platform',
      yielding: 'Pulled aside for traffic',
      held: 'Held behind a train',
      noRoute: 'No route',
      stranded: 'Stranded',
      noFuel: 'Out of fuel',
      noPower: 'No power',
      overweight: 'Overweight',
    } as Record<string, string>,
  },
  contracts: {
    title: 'Contract Board',
    sideTitle: 'Contracts',
    offers: 'Offers',
    active: 'Active',
    history: 'Recent',
    accept: 'Accept',
    decline: 'Decline',
    deadline: 'Deadline once accepted',
    timeLeft: 'Time left',
    offerExpires: (t: string) => `offer expires in ${t}`,
    noOffers: 'No offers right now. New ones arrive every few hours.',
    needStations: 'Offers appear once a station produces something another station accepts.',
    noActive: 'No active contracts.',
    noHistory: 'Nothing delivered yet.',
    done: 'Delivered',
    failed: 'Deadline missed',
    expired: 'Expired',
    accepted: (n: string) => `${n} accepted`,
    completed: (n: string, pay: string) => `${n} delivered: ${pay}`,
    failedMsg: (n: string, rep: number) => `${n} failed: -${rep} reputation`,
    stats: (done: number, failed: number) => `${done} delivered · ${failed} failed`,
    offersBadge: (n: number) => `${n} new`,
    sideEmpty: 'No active contracts.',
    sideEmptyOffers: 'Offers waiting on the board.',
    dailyTicket: "Daily bonus: +1 ticket for yesterday's deliveries",
  },
  gacha: {
    title: 'Rolling Stock Works',
    banners: 'Banners',
    pull: 'Pull',
    rates: 'Rates',
    rules: (pity: number) => `SSR guaranteed within ${pity} pulls. 10x guarantees at least one R.`,
    pity: (n: number, max: number) => `Pity ${n} / ${max}`,
    pull1: (c: number) => `Pull x1 (${c} ticket)`,
    pull10: (c: number) => `Pull x10 (${c} tickets)`,
    poolSize: (n: number) => `${n} items in the pool`,
    idleHint: 'Tickets come from contracts and daily deliveries. No real money, ever.',
    noTickets: 'Not enough tickets',
    loco: 'Locomotive',
    wagon: 'Wagon',
    newItem: 'NEW',
    dupe: (n: number, need: number) => `Duplicate: ${n} / ${need} to next level`,
    levelUp: (l: number) => `Level up! Now Lv ${l}`,
    guaranteed: 'guaranteed',
    collect: 'Collect',
    ssrToast: (n: number) => `${n} SSR pulled!`,
    featured: (days: number, pct: number) =>
      `Featured (rate-up ${pct}% of their rarity) · rotates in ${days}d`,
    featuredBadge: 'featured',
  },
  roster: {
    title: 'Roster',
    kind: 'Kind',
    rarity: 'Rarity',
    sort: 'Sort',
    all: 'All',
    name: 'Name',
    level: 'Level',
    newest: 'Newest',
    freeOnly: 'Unassigned only',
    count: (n: number) => `${n} items`,
    empty: 'Nothing matches.',
    capacity: 'Capacity',
    crew: 'crew',
    type: { steam: 'Steam', diesel: 'Diesel', electric: 'Electric' } as Record<string, string>,
    carries: {
      liquid: 'Liquids (water, oil)',
      mineral: 'Minerals (coal, stone, iron)',
      bulk: 'Bulk (wood, wheat)',
      people: 'Passengers',
    } as Record<string, string>,
    fuelLine: (l: {
      type: string;
      fuelCap?: number;
      fuelPerTile?: number;
      waterCap?: number;
      waterPerTile?: number;
      powerPerTile?: number;
    }) =>
      l.type === 'steam'
        ? `Steam · ${l.fuelCap} fuel, ${l.waterCap} water · ${l.fuelPerTile}/${l.waterPerTile} per tile`
        : l.type === 'diesel'
          ? `Diesel · ${l.fuelCap} oil · ${l.fuelPerTile} per tile`
          : `Electric · ${l.powerPerTile} power per tile`,
    maxLevel: 'Max level',
    dupeProgress: (n: number, need: number) => `Duplicates ${n} / ${need} to next level`,
    assignedTo: (n: string) => `In service: ${n}`,
    inDepot: 'In depot',
  },
  settings: {
    title: 'Settings',
    options: 'Options',
    saves: 'Saves',
    audio: 'Audio',
    master: 'Master volume',
    sfx: 'Effects',
    music: 'Music',
    audioNote:
      'Sounds and music are synthesized at runtime; an .ogg at /assets/audio/<event>.ogg overrides a synthesized effect.',
    gameplay: 'Gameplay',
    edgeScroll: 'Edge scrolling',
    autosave: 'Autosave (every minute)',
    dayNight: 'Day / night cycle',
    smoke: 'Locomotive smoke',
    weather: 'Weather and seasons',
    showFps: 'Show FPS',
    on: 'On',
    off: 'Off',
    controls: 'Controls',
    controlsText:
      'WASD / arrows / middle-drag pan · wheel zoom · M overview · Tab next item · R rotate · Right-click / Delete remove · Esc cancel · Space pause · 1 2 3 speed · F depot · C contracts · G gacha · V roster · K market · ` debug',
    lastSave: 'Last save',
    version: 'Save format',
    save: 'Save now',
    load: 'Load last save',
    newGame: 'New game',
    newGameNote: 'Generates a fresh map. Leave the seed empty for a random one.',
    seedPlaceholder: 'seed (optional)',
    confirmNew: 'Start a new game? The current save will be replaced on the next autosave.',
    transfer: 'Transfer',
    exportSave: 'Export to text',
    importSave: 'Import from text',
    confirmImport: 'Replace the current game with the pasted save?',
    saved: 'Game saved',
    loaded: 'Save loaded',
    saveFailed: 'Could not save (storage full or blocked)',
    noSave: 'No save found',
    badSave: 'Save data unreadable',
  },
  menu: {
    tagline: 'Rails, contracts and the luck of the draw',
    continue: 'Continue',
    newGame: 'New game',
    tuning: 'Game tuning',
    content: 'Content editor',
    modified: '(modified)',
    levels: 'Levels',
    noLevels: 'No saved levels yet. Create one below or import a level.',
    play: 'Play',
    edit: 'Edit',
    delete: 'Delete',
    confirmDelete: (n: string) => `Delete level "${n}"?`,
    newLevel: 'New level',
    blank: 'Blank',
    generated: 'Generated',
    importLevel: 'Import level',
    importHint: 'Paste a level JSON here',
    paused: 'Paused',
    resume: 'Resume',
    backToEditor: 'Back to editor',
    mainMenu: 'Main menu',
    confirmReplace: 'This replaces the current saved game. Continue?',
    menuButton: 'Menu',
  },
  editor: {
    terrainDesc: 'Paint this terrain. Anything built on the tile is cleared.',
    title: 'Level editor',
    name: 'Name',
    size: 'Size',
    description: 'Description shown in the level list',
    start: 'Player start',
    startTier: 'Start tier',
    brush: 'Terrain brush',
    brushHint:
      'Pick a terrain in the toolbar, drag to paint. Painting clears anything built on the tile.',
    fill: (t: string) => `Fill ${t}`,
    regenerate: 'Regenerate map',
    file: 'Level',
    save: 'Save level',
    saveAs: 'Save as...',
    playTest: 'Play test',
    exit: 'Exit to menu',
    saved: (n: string) => `Level "${n}" saved`,
    saveFailed: 'Could not save the level (storage full?)',
    badLevel: 'That is not a level file',
    unsaved: 'Unsaved changes will be lost. Continue?',
    hint: 'Editor: free building, all regions open, clock stopped. Esc for the menu.',
    terrain: 'Terrain',
    levelDown: 'Level -',
    levelUp: 'Level +',
    newName: 'Level name',
  },
  tuning: {
    title: 'Game tuning',
    newGameOnly: 'new map',
    progression: 'Progression',
    tiers: 'Reputation tier thresholds',
    tiersHint: 'Comma-separated, first is 0. Tiers unlock regions, station levels and banners.',
    note: 'Changes apply immediately and are stored with the save. Map values apply to the next generated map.',
    reset: 'Reset to defaults',
  },
  content: {
    title: 'Content editor',
    tabs: {
      locomotives: 'Locomotives',
      wagons: 'Wagons',
      cargo: 'Cargo',
      stations: 'Stations',
      contracts: 'Contracts',
      decor: 'Decor',
      buildings: 'Buildings',
      gacha: 'Gacha',
      track: 'Track',
    } as Record<string, string>,
    customActive: 'Custom content active',
    shipped: 'Shipped content',
    levels: 'Level table',
    entries: 'Entries',
    config: 'Configuration',
    duplicate: 'Duplicate',
    remove: 'Remove',
    add: 'Add entry',
    export: 'Export JSON',
    import: 'Import JSON',
    jsonHint: 'bundle JSON',
    badJson: 'Invalid JSON',
    reset: 'Reset to shipped data',
    confirmReset: 'Discard all custom content and reload?',
    apply: 'Apply and reload',
    applyNote: 'Applying reloads the page; the current game is saved first.',
  },
  train: {
    title: 'Train',
    consist: 'Consist and tanks',
    tripStats: 'Loop statistics',
    gone: 'This train is no longer in service.',
    state: 'State',
    note: 'Note',
    speed: 'Top speed',
    crew: 'Crew',
    haul: 'Hauled weight / engine power (t)',
    engines: 'Engines',
    fuel: 'Fuel',
    water: 'Water',
    oil: 'Oil',
    power: 'Power',
    stockPower: (n: number) => `${n} in the battery`,
    perTile: 'Use per tile',
    range: 'Range on current tanks',
    tiles: 'tiles',
    prefer: 'Steam fuel:',
    coal: 'Coal',
    wood: 'Wood',
    lastLoop: 'Last loop',
    currentLoop: 'Current loop',
    noTrip: 'No completed loop yet.',
    distance: 'Distance',
    fuelUsed: 'Consumed',
    refuelled: 'Refuelled',
    gathered: 'Gathered',
    delivered: 'Delivered',
    income: 'Income',
    emergency: 'Emergency refuel (2x cost)',
    emergencyHint: 'Fills the tanks from the stockpile at double cost, wherever the train is.',
    emergencyDone: (s: string) => `Delivered by road: ${s}`,
    emergencyNone: 'Nothing in the stockpile to send',
  },
  market: {
    title: 'Market',
    resource: 'Resource',
    have: 'Stockpile',
    buyPrice: 'Buy',
    sellPrice: 'Sell',
    buy: 'Buy',
    sell: 'Sell',
    full: 'Stockpile is full',
    hint: 'Prices are fixed per unit. Warehouses raise the stockpile cap.',
  },
  res: {
    power: 'Power (battery)',
    population: 'Population',
    populationHint:
      'People working at stations, works, services and on trains. Each eats wheat every day; the ones not inside a building walk about.',
    people: 'People',
    eats: 'Eats',
    famine: 'NO WHEAT',
    wheatPerDay: 'wheat/day',
    openMarket: 'Open the market',
    have: 'Stockpile / cap',
    producedDay: 'Produced / day',
    consumedDay: 'Consumed / day',
    netDay: 'Net / day',
    info: {
      water: 'From Water Pumps. Steam engines drink it; the refinery and power plant use it.',
      wheat: 'From farms. Food for every crew member; run out and everything slows.',
      stone: 'From quarries. Builds track and buildings; the grinder turns it into iron.',
      wood: 'From lumber yards. Builds almost everything; the kiln turns it into coal; steam engines can burn it.',
      coal: 'From charcoal kilns or the Market. Steam engine fuel and power plant feed.',
      oil: 'From the refinery or the Market. Diesel engine fuel; the power plant can burn it too.',
      iron: 'From the stone grinder or the Market. Switches, signals, power lines and works.',
      power:
        'From power plants, stored in the battery. Electric engines draw it while on powered rails.',
    } as Record<string, string>,
  },
  fleet: {
    needLoco: 'A train needs at least one locomotive',
    tooManyLocos: (n: number) => `At most ${n} locomotives`,
    tooManyWagons: (n: number) => `At most ${n} wagons`,
    locoUnavailable: 'Locomotive unavailable',
    wagonUnavailable: 'Wagon unavailable',
    tooHeavy: (w: number, p: number) => `Wagons weigh ${w} t, engines haul ${p} t`,
    needTwoStops: 'Route needs at least two stations',
    missingStation: 'Missing station',
    noPlatform: (n: string) => `${n} has no platform track`,
    cannotPlace: 'Could not place train',
  },
  topbar: {
    depot: 'Depot',
    contracts: 'Contracts',
    gacha: 'Gacha',
    roster: 'Roster',
    market: 'Market',
    settings: 'Settings',
    cheat: 'Cheat',
    cheated: '+$10,000 and every resource topped up',
  },
  station: {
    level: (l: number) => `Level ${l}`,
    biome: 'Biome',
    produces: 'Produces',
    accepts: 'Accepts',
    storage: 'Storage',
    platforms: 'Platforms',
    loadRate: 'Loading',
    perDay: (v: number) => `${v} / day`,
    perSec: (v: number) => `${v} / s`,
    upgrade: 'Upgrade',
    upgradeTo: (l: number, cost: string) => `Upgrade to ${l} (${cost})`,
    maxed: 'Max level',
    unlocks: (c: string) => `Next: ${c}`,
    demolish: 'Demolish',
    rename: 'Rename',
    noPlatform: 'No adjacent track!',
    orphaned: (n: string) => `${n} lost its platform track`,
    boost: (pct: number) => `Water tower: loading +${pct}%`,
    market: 'Spot market',
    marketHint: 'Paid for cargo without a contract. Demand recovers over a day.',
    contracts: 'Contracts here',
  },
} as const;
